image: ubuntu:24.04

stages:
  - build

build-jobs:
  stage: build
  script:
    - echo "Installing dependencies"
    - apt update && apt install -y debmake debhelper-compat packaging-dev
    - echo "Building package"
    - dpkg-buildpackage -nc -i
